# Generated by Django 3.2.7 on 2021-09-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=250)),
                ('supplier_code', models.CharField(max_length=25)),
                ('supplier_address', models.TextField()),
            ],
            options={
                'verbose_name': ('supplier',),
                'verbose_name_plural': 'suppliers',
            },
        ),
    ]
