# Generated by Django 3.2.7 on 2021-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='score',
            field=models.IntegerField(default=1),
        ),
    ]
