# Generated by Django 3.2.7 on 2021-09-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='score',
            new_name='credit',
        ),
    ]
