# Generated by Django 3.2.7 on 2021-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_rename_score_supplier_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='credit',
            field=models.IntegerField(default=5),
        ),
    ]
