# Generated by Django 3.2.7 on 2021-09-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='credit',
            new_name='credit_score',
        ),
    ]
